AWSTemplateFormatVersion: 2010-09-09
Description: |
  The Roman Numerals Converter Application aims to convert 
  the given number to the Roman numerals. The application
  is to be coded in Python and deployed as a web application with 
  Flask on AWS Elastic Compute Cloud (EC2) 
  Instance using AWS Cloudformation and CLI Services.
Parameters:
  Keypair:
    Description: Enter the name of your key please
    Type: AWS::EC2::KeyPair::KeyName
    Default: 



Metadata:
  
Mappings:
  
Conditions:
  
Resources:
WebserverSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enables SSH and HTTP # Required
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
webserverhost:
  Type: AWS::EC2::Instance
  Properties:
    
    ImageId: ami-05fa00d4c63e32376
    InstanceType: t2.micro
    KeyName: !Ref Keypair
    SecurityGroupIds:
      SecurityGroupIds
    SecurityGroups:

Transform:
  
Outputs: