AWSTemplateFormatVersion: 2010-09-09
Description: |
security grup oluşturmak için yazıldı.
 
Resources:
  LogicalID:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 30092022SecGroup
      GroupName: "String"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

